#!/bin/sh
#
#
# This file is edited by vim
#

show_progress_bar() {
    USED=`expr \( $1 + 1 \) / 2`
    FREE=`expr 50 - $1 / 2`
    if [ ${USED} -ne 0 ]; then
        printf "\033[41m%${USED}s"
    fi
    if [ ${FREE} -ne 0 ]; then
        printf "\033[46m%${FREE}s"
    fi
    printf "\033[m"
}

show_disk_usage() {
 
 #   ls -d /net/mail > /dev/null
 #   ls -d ${HOME} > /dev/null
 #   case ${OS} in
        QINFO=`quota -AQvw | sort -u`
 #       *) QINFO=`quota -v | sort -u` ;;
 #   esac

    printf "\033[1;33m= Disk Usage =================================================================\033[m\n"

    HOMEKEY=`cd ${HOME} && pwd -P | awk -F/ '{print $3}'`
 #   MAILKEY="mail"
    MAILKEY=`cd ${HOME} && pwd -P | awk -F/ '{print $3}'`
    TYPE_LIST=`echo "${MAILKEY} ${HOMEKEY}"`
#    TYPE_LIST=`echo "${HOMEKEY}"`

#    for TYPE in ${TYPE_LIST}; do
#        Q=`echo "${QINFO}" | egrep "${TYPE}"`
#        #Q_FULL=`echo ${Q} | awk '{print $3}'`
#        #Q_USED=`echo ${Q} | awk '{print $2}' | awk -F'*' '{print $1}'`
#	Q_FULL="10000"
#	Q_USED="3600"

	Q_FULL=`quota -AQvw | sort -u | egrep "centos-home" | awk -F'[ *]*' '{print $4}'`
	Q_USED=`quota -AQvw | sort -u | egrep "centos-home" | awk -F'[ *]*' '{print $2}'`
#	echo ${Q_FULL}
#	echo ${Q_USED}





        if [ -n "${Q_FULL:=0}" -a ${Q_FULL} -gt 0 ]; then
            PERCENT=`expr ${Q_USED} \* 100 / ${Q_FULL}`

#            if [ "${TYPE}" = "mail" ]; then
#                TYPENAME="Mail"
#            else
                TYPENAME="Home"
#            fi

            printf " \033[1m${TYPENAME}:\033[m "
            show_progress_bar ${PERCENT}

            if [ ${PERCENT} -lt 5 -o ${PERCENT} -gt 95 ]; then
                printf " ${PERCENT}%% ${Q_USED}/${Q_FULL} KB\n"
            else
                printf " ${PERCENT}%% `expr ${Q_USED} / 1000`/`expr ${Q_FULL} / 1000` MB\n"
            fi

            if [ ${PERCENT} -gt 100 ]; then
#                if [ "${TYPE}" = "mail" ]; then
#                    printf "\033[1;5;31mBoom!!\033[m \033[1;33m Your Mailbox is out of quota limit! Reduce it immediately!\033[m\n"
#                else
                    printf "\033[1;5;31mBoom!!\033[m \033[1;33m Your HomeDir is out of quota limit! Reduce it immediately!\033[m\n"
#                fi
            else
                echo
            fi
        fi
#    done
}

showInfoAndExecShell() {
	/usr/lib/lab-script/mkmotd

	# User's process Status
	printf "\033[40;33m= Process ==============================================================\033[0m\n"
	ps

	# Workstation Status
	printf "\033[40;33m= Information ==========================================================\033[0m\n"
	printf "\033[40;32mCurrent Time:\033[0m "
	date
	printf "\033[40;32mOnline Users:\033[0m "
	who -q | tail -1 | awk -F'=' '{print $2}'

	# check if user's SHELL has been installed
	if [ ! -f ${SHELL} ]; then
		echo "Sorry, your login shell ($(SHELL)) has not been installed on this machine"
		echo "Use /bin/sh as your default shell :)"
	fi

	# Login shell uses "-l", except sh
	if [ "${SHELL}" != "/bin/sh" ]; then
		exec ${SHELL} -l
	else
		source /etc/profile
		exec ${SHELL}
	fi
}

###
# main() flow
###

# For remote command execution
if [ -n "${SSH_ORIGINAL_COMMAND}" ]; then
	exec ${SHELL} -c "${SSH_ORIGINAL_COMMAND}"
fi

# Excute shell
if [ $# -eq 0 ]; then   # interactive shell
	showInfoAndExecShell
else					# non-interactive shell
	exec ${SHELL} $1 "$2"
fi
